/**
 * Wortliste für Shortcode-Generierung (Phase 9)
 * 
 * 600 positive 4-Buchstaben-Wörter für das Shortcode-System
 * Format: "WORT 1234"
 */

export const WORD_LIST = [
  "ACID", "ACTS", "AKKU", "ALPS", "AREA", "ARMY", "ATOM", "AUTO",
  "BABY", "BACH", "BALL", "BAND", "BANK", "BASE", "BASS", "BAUM", 
  "BEAR", "BEAT", "BEER", "BEIN", "BELL", "BERG", "BEST", "BIER", 
  "BIKE", "BILD", "BIRD", "BITE", "BLAU", "BLUE", "BOAT", "BODY", 
  "BOLD", "BOOK", "BOOM", "BOOT", "BOSS", "BOYS", "BROT", "BUBE", 
  "BUCH", "BULK", "BUNT", "BURG", "BURN", "CAFE", "CAKE", "CALL", 
  "CAMP", "CARD", "CARE", "CASE", "CASH", "CAST", "CENT", "CHAT", 
  "CHEF", "CHIC", "CHIN", "CHIP", "CITY", "CLAN", "CLAP", "CLIP", 
  "CLUB", "CODE", "COLA", "COLD", "COME", "COOK", "COOL", "COPY", 
  "CORE", "CORN", "COST", "CREW", "CUBE", "CULT", "CUTE", "DACH", 
  "DAME", "DANK", "DARE", "DARK", "DATA", "DATE", "DAWN", "DAYS", 
  "DEAL", "DEAR", "DECK", "DEEP", "DEKO", "DEMO", "DESK", "DIET", 
  "DING", "DIRT", "DISC", "DISH", "DIVA", "DOCK", "DOLL", "DOOR", 
  "DOPE", "DORF", "DOSE", "DOWN", "DRAW", "DREI", "DROP", "DRUM", 
  "DUAL", "DUCK", "DUFT", "DUKE", "DUST", "DUTY", "EASY", "ECHO", 
  "ECHT", "ECKE", "EDEL", "EDGE", "EDIT", "EINS", "EISEN", "ELFE", 
  "ENDE", "ENTE", "EPIC", "ERDE", "ESEL", "EURO", "EXIT", "EYES", 
  "FACE", "FACH", "FACT", "FAIR", "FALL", "FAME", "FANS", "FARE", 
  "FARM", "FAST", "FAUL", "FEAR", "FEAT", "FEED", "FEEL", "FEET", 
  "FEIN", "FELS", "FEST", "FILM", "FINE", "FIRE", "FISH", "FIVE", 
  "FLAG", "FLAT", "FLIP", "FLOW", "FLUG", "FLUT", "FOAM", "FOIL", 
  "FOLD", "FOOD", "FOOL", "FOOT", "FORD", "FORM", "FORT", "FOTO", 
  "FOUR", "FRAU", "FREE", "FREI", "FROG", "FROH", "FUEL", "FULL", 
  "FUND", "FUNK", "FUSE", "GAIN", "GAME", "GANG", "GANS", "GAST", 
  "GATE", "GAUL", "GEAR", "GELD", "GENE", "GENF", "GERN", "GIFT", 
  "GIRL", "GIVE", "GLAD", "GLAM", "GLAS", "GLOW", "GOAL", "GOAT", 
  "GOLD", "GOLF", "GONE", "GOOD", "GOTT", "GRAB", "GRAD", "GRAM", 
  "GRAS", "GRAU", "GRAY", "GREY", "GRIP", "GROW", "GURU", "HAAR", 
  "HAIL", "HAIR", "HALL", "HALO", "HALS", "HALT", "HAND", "HANG", 
  "HARD", "HARM", "HASE", "HATS", "HAUS", "HAUT", "HEAD", "HEAR", 
  "HEAT", "HEFT", "HEIM", "HELD", "HELM", "HELP", "HEMD", "HERB", 
  "HERD", "HERO", "HERR", "HERZ", "HIER", "HIGH", "HIKE", "HILL", 
  "HIRE", "HIRN", "HITS", "HOCH", "HOLD", "HOLE", "HOLY", "HOLZ", 
  "HOME", "HOOD", "HOOK", "HOPE", "HORN", "HOSE", "HOST", "HOUR", 
  "HUHN", "HULL", "HUND", "HUNT", "HYPE", "ICON", "IDEA", "IDOL", 
  "IGEL", "INCH", "INFO", "IRON", "ITEM", "JACK", "JAGD", "JAHR", 
  "JAZZ", "JEAN", "JEEP", "JOKE", "JUMP", "JUNG", "JURY", "JUST", 
  "KAHN", "KALT", "KAMM", "KANU", "KATZ", "KAUF", "KEEN", "KEEP", 
  "KEKS", "KERN", "KICK", "KIDS", "KIND", "KING", "KINO", "KISS", 
  "KITE", "KIWI", "KLAR", "KNIE", "KNOB", "KNOT", "KNOW", "KOCH", 
  "KOHL", "KOPF", "KORB", "KORN", "KRAN", "KULT", "KURS", "KURZ", 
  "KUSS", "LABS", "LACE", "LACH", "LACK", "LADE", "LADY", "LAGE", 
  "LAKE", "LAMB", "LAMP", "LAND", "LANE", "LANG", "LAST", "LATE", 
  "LAUT", "LAWN", "LEAD", "LEAF", "LEAN", "LEFT", "LEIM", "LEIN", 
  "LENS", "LESS", "LESE", "LIED", "LIFE", "LIFT", "LIKE", "LILA", 
  "LIME", "LINE", "LINK", "LION", "LIST", "LIVE", "LOAD", "LOAN", 
  "LOBE", "LOCH", "LOCK", "LOGO", "LOHN", "LONG", "LOOK", "LOOP", 
  "LORD", "LOST", "LOUD", "LOVE", "LUCK", "LUFT", "LUSH", "LUST", 
  "LUXE", "MACH", "MADE", "MAHL", "MAID", "MAIL", "MAIN", "MAIS", 
  "MAKE", "MALE", "MALL", "MAMA", "MANN", "MARK", "MARS", "MASK", 
  "MASS", "MAST", "MATE", "MATH", "MAUS", "MEAL", "MEAN", "MEAT", 
  "MEER", "MEET", "MEGA", "MEHL", "MEHR", "MEIN", "MELT", "MEMO", 
  "MENU", "MESH", "MESS", "MIKE", "MILD", "MILE", "MILK", "MILL", 
  "MIND", "MINE", "MINI", "MINT", "MISS", "MODE", "MOND", "MOOD", 
  "MOON", "MOOS", "MORE", "MOST", "MOVE", "MUCH", "MULE", "MUND", 
  "MUSE", "MUST", "NACH", "NAHE", "NAIL", "NAME", "NASE", "NASS", 
  "NAVY", "NEAR", "NEAT", "NECK", "NEED", "NEON", "NEST", "NETZ", 
  "NEWS", "NEXT", "NICE", "NINE", "NOCH", "NOON", "NORD", "NOSE", 
  "NOTE", "NOVA", "NULL", "OATH", "OBEN", "OBST", "OFEN", "OKAY", 
  "ONCE", "ONLY", "OPEN", "OPER", "ORAL", "OVER", "PAAR", "PACE", 
  "PACK", "PAGE", "PAIN", "PAIR", "PALM", "PAPA", "PARK", "PART", 
  "PASS", "PAST", "PATH", "PEAK", "PEAR", "PEEL", "PEEP", "PELZ", 
  "PFAD", "PICK", "PILE", "PILL", "PILZ", "PINE", "PINK", "PINT", 
  "PIPE", "PLAN", "PLAY", "PLOT", "PLUG", "PLUS", "POEM", "POET", 
  "POLE", "POLL", "POND", "PONY", "POOL", "POOR", "POPS", "PORT", 
  "POSE", "POSH", "POST", "POUR", "PRAY", "PURE", "PUSH", "PUTZ", 
  "QUER", "QUIT", "RACE", "RACK", "RAIN", "RAKE", "RAMP", "RAND", 
  "RANG", "RARE", "RATE", "RAUM", "RAUS", "RAVE", "RAYS", "READ", 
  "REAL", "REAR", "RELY", "RENT", "REST", "RICH", "RIDE", "RING", 
  "RIOT", "RISE", "RISK", "ROAD", "ROAR", "ROBE", "ROCK", "RODS", 
  "ROLE", "ROLL", "ROOF", "ROOM", "ROOT", "ROPE", "ROSE", "ROST", 
  "RUBY", "RUHE", "RULE", "RUND", "RUSH", "RUST", "SAAL", "SAAT", 
  "SACK", "SAFE", "SAFT", "SAGE", "SAIL", "SALE", "SALT", "SALZ", 
  "SAME", "SAND", "SATT", "SATZ", "SAVE", "SCAN", "SCAR", "SEAL", 
  "SEAT", "SEED", "SEEK", "SEEN", "SEHR", "SEIL", "SEIN", "SEIT", 
  "SELL", "SEND", "SENF", "SETS", "SEXY", "SHED", "SHIP", "SHOE", 
  "SHOP", "SHOT", "SHOW", "SHUT", "SIDE", "SIEG", "SIGN", "SILK", 
  "SING", "SINK", "SINN", "SITZ", "SIZE", "SKIN", "SKIP", "SLAB", 
  "SLAM", "SLAP", "SLIM", "SLIP", "SLOT", "SLOW", "SNAP", "SNOW", 
  "SOAP", "SOAR", "SOCK", "SODA", "SOFA", "SOFT", "SOHN", "SOIL", 
  "SOLD", "SOLE", "SOLL", "SOLO", "SONG", "SOON", "SORT", "SOUL", 
  "SOUP", "SOUR", "SPAN", "SPIN", "SPIT", "SPOT", "SPUR", "STAB", 
  "STAR", "STAY", "STEM", "STEP", "STEW", "STIL", "STOP", "SUIT", 
  "SURE", "SURF", "SWAG", "SWAN", "SWIM", "SYNC", "TACT", "TAGE", 
  "TAIL", "TAKE", "TALE", "TALK", "TALL", "TANK", "TANZ", "TAPE", 
  "TASK", "TAXI", "TEAM", "TEAR", "TECH", "TEIG", "TEIL", "TELL", 
  "TENT", "TERM", "TEST", "TEXT", "THAT", "THEN", "THIS", "TIDE", 
  "TIDY", "TIEF", "TIER", "TILE", "TILL", "TIME", "TINT", "TINY", 
  "TIPS", "TIRE", "TOLL", "TONE", "TOOL", "TOPF", "TOPS", "TOUR", 
  "TOWN", "TOYS", "TRIM", "TRIP", "TRUE", "TUBE", "TUNA", "TUNE", 
  "TURM", "TURN", "TWIN", "TYPE", "UFER", "UNIT", "URNE", "USER", 
  "VASE", "VEIL", "VENT", "VERS", "VEST", "VIBE", "VICE", "VIEH", 
  "VIEL", "VIER", "VIEW", "VINE", "VIPS", "VOID", "VOLK", "VOLL", 
  "VOLT", "VOTE", "WACH", "WAGE", "WAHL", "WAHN", "WAHR", "WAIT", 
  "WAKE", "WALD", "WALK", "WALL", "WAND", "WANT", "WARD", "WARM", 
  "WART", "WASH", "WASP", "WAVE", "WAYS", "WEAK", "WEAR", "WEEK", 
  "WEIN", "WEIT", "WELL", "WELT", "WERK", "WERT", "WEST", "WETT", 
  "WHAT", "WHEN", "WHIP", "WIDE", "WIFE", "WILD", "WILL", "WIND", 
  "WINE", "WING", "WINK", "WIRE", "WIRT", "WISH", "WITH", "WITZ", 
  "WOHL", "WOLF", "WOOD", "WOOL", "WORD", "WORK", "WORM", "WORT", 
  "WRAP", "WUND", "WURF", "YARD", "YARN", "YEAH", "YEAR", "YOGA", 
  "ZAHL", "ZAHN", "ZAUN", "ZEHN", "ZEIT", "ZELT", "ZERO", "ZIEL", 
  "ZIMT", "ZINK", "ZONE", "ZOOM", "ZORN"
] as const;

/**
 * Anzahl der Wörter in der Liste
 */
export const WORD_COUNT = WORD_LIST.length;

/**
 * Shortcode-Format Konstanten
 */
export const SHORTCODE_WORD_LENGTH = 4;
export const SHORTCODE_NUMBER_LENGTH = 4;
export const SHORTCODE_NUMBER_MIN = 0;
export const SHORTCODE_NUMBER_MAX = 9999;
